config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resource :users
  resource :posts
  resources :comments 
  

  root :to => 'users#index'

  get '/feed', to: "posts#index"
  get '/home', to: "users#index"
  get '/edit_my_profile', to: "users#edit"
  get '/user/:username', to: 'users#show'
  get '/post/:id', to: 'posts#show'
  get '/comment/:id', to: 'comments#show'
  get '/users_list', to: 'users#list'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
  mount_uploaders :photos, PhotosUploader
  serialize :photos, JSON # If you use SQLite, add this line.

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true

  mount_uploader :avatar, AvatarUploader
  has_many :posts
  after_create :set_default_avatar

  def set_default_avatar
    self.avatar = File.open(Rails.root + "app/assets/images/avatar.jpeg")
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :username, :avatar)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :username)}
          end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @post = Post.find_by id: params[:id]
    @comments = @post.comments 
    @authors = posts_authors
    @comment = Comment.new
  end

  def index

  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @post = Post.find_by id: params[:id]
    @comment.post_id = comment_params[:post_id]

    if @comment.text != ""
      @comment.save!
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :text, {photos: []}, :files)
  end

  def posts_authors
    User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #@post.photos = params[:photos]
    @post.save!
    redirect_to root_path
  end

  def edit
  end

  def destroy
  end

  def show
    @post = Post.find_by id: params[:id] 
    @authors = posts_authors
  end

  def index
    @posts = get_all_posts
    @authors = posts_authors
  end

  private

  def get_all_posts
    posts = Post.all.order('created_at desc')
  end

  def posts_authors
    User.all
  end

  def post_params
    params.require(:post).permit(:user_id, :name, :text, {photos: []}, :files)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Встроенный в девайз фильтр — посылает незалогиненного пользователя
  before_action :authenticate_user!

  # Задаем объект @user для шаблонов и экшенов
  before_action :set_current_user

  def edit
  end

  def update
    change_user_data(params)
    redirect_to home
  end

  def index
    @posts = Post.where("user_id = '#{current_user.id}'")
  end

  def set_current_user
    @user = current_user
  end

  def show
    @user = User.find_by username: params[:username]
    @posts = Post.where("user_id = '#{@user.id}'")
  end

  def list
    @users = User.all
  end

  private

  def change_user_data(params)
    @user.username = params[:username]
    @user.name = params[:name]
    @user.avatar = params[:avatar]
    @user.save!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar.nil?
      avatar = path_to_image("avatar.jpeg")
    else
      user.avatar
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<div class="container">
	<div class="row text-center">
		<h1><%= @post.name %> @<%= @authors.find_by(id: @post.user_id).username %></h1>  <br>
		<%= link_to "Читать полностью", controller: "posts", action: "show", id: @post.id %>		
	</div>

	<div class="row text-center buffer-both buffer-top">
		<%= form_for @comment do |f| %>

	    <div class="field">
	    <%= f.label :Комментарий %> <br>
	    <%= f.text_area(:text, :onkeyup => "checkParams()") %>
	    </div> 

	    <%= f.hidden_field :user_id %>
	    <%= f.hidden_field :post_id, value: @post.id %>

	    <br>
	    <%= f.submit "Отправить комментарий", disabled: true, :id => "submit" %>

	    <% end %>
	</div>

	<% @comments.reverse.each do |com| %>
	<div class="row comment-block">
		<div class="col-md-2 text-center">
			<%= image_tag(User.find_by(id: com.user_id).avatar.url, :class => "avatar-min") %>
			<h2>@<%= User.find_by(id: com.user_id).username %></h2>
		</div>
		<div class="col-md-10 comment-text">
			<h4 class="buffer-top"><%= com.text %></h4>
		</div>
	</div>
	<% end %>

	<script type="text/javascript">
		function checkParams() {
			var text = $('#comment_text').val();

			if(text.length != 0) {
        	$('#submit').removeAttr('disabled');
    		} else {
        	$('#submit').attr('disabled', 'disabled');
    }
		}
	</script>

</div>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
        
<div class="container user-block text-center buffer-top">
    <div class="row">
    	
        <% @posts.each do |post| %>

        <% if !post.photos.blank? %>
            <div class="col-md-6">
               <div class="scroller">
                    <% post.photos.each do |photo| %>
                   <div>
                        <%= image_tag(photo.url, :class => "post-photo") %>
                    </div>
                    <% end %>
               </div>
            </div> 

            <div class="col-md-6">
                <div class="post-block">
                    <div class="post-name">
                        <h1><%= post.name %> @<%= @authors.find_by(id: post.user_id).username %></h1> <h4>   <%= post.created_at.strftime('%d.%m.%Y - %k:%M') %></h4> <br>
                        <%= link_to "Читать полностью", controller: "posts", action: "show", id: post.id %>
                        <%= link_to "Обсуждение", controller: "comments", action: "show", id: post.id %> (<%= post.comments.size %>)
                    </div>
                    <div class="post-text">
                        <p><%= post.text %></p> 
                    </div>
                </div>
            </div>
            <% else %>
            <div class="col-md-12">
                <div class="post-block-full">
                    <div class="post-name">
                        <h1><%= post.name %> @<%= @authors.find_by(id: post.user_id).username %></h1> <h4>   <%= post.created_at.strftime('%d.%m.%Y - %k:%M') %></h4> <br>
                        <%= link_to "Читать полностью", controller: "posts", action: "show", id: post.id %> <br>
                        <%= link_to "Обсуждение", controller: "comments", action: "show", id: post.id %> (<%= post.comments.size %>)
                    </div>
                    <div class="post-text">
                        <p><%= post.text %></p> 
                    </div>
                </div>
            </div>
            <% end %>

    <% end %>
   
    </div>  
</div>

app/views/posts/new.html.erb
<div class="container text-center">
 <div class="row">
    <%= form_for @post do |f| %>

    <div class="field">
    <%= f.label :Название_поста %> <br>
    <%= f.text_field(:name, :onkeyup => "checkParams()")%>
    </div> 

    <div class="field">
    <%= f.label :Текст %> <br>
    <%= f.text_area(:text, :onkeyup => "checkParams()")%>
    </div> 

    <div class="field">
    <%= f.label :Фотографии %> <br>
    <%= f.file_field :photos, multiple: true, :style => "display: inline;" %>
    </div> 

    <div class="field">
    <%= f.label :Файлы %> <br>
    <%= f.file_field :files, multiple: true, :style => "display: inline;" %>
    </div> 

    <%= f.hidden_field :user_id %>

    <br>
    <%= f.submit "Создать пост", disabled: true, :id => "submit" %>

    <% end %>
 </div>   
</div>    

<script type="text/javascript">
      function checkParams() {
         var text = $('#post_text').val();
         var name = $('#post_name').val();

         if(text.length != 0 && name.length != 0) {
         $('#submit').removeAttr('disabled');
         } else {
         $('#submit').attr('disabled', 'disabled');
    }
      }
   </script>

app/views/posts/show.html.erb
<div class="container user-block text-center buffer-top">
    <div class="row">

        <div class="row">
            <div class="col-md-12">
                <div class="post-block-full">
                    <div class="post-name">
                        <h1><%= @post.name %> @<%= @authors.find_by(id: @post.user_id).username %></h1>  <br>
                        <%= link_to "Обсуждение", controller: "comments", action: "show", id: @post.id %> (<%= @post.comments.size %>)
                    </div>
                    <div class="post-text">
                        <p><%= @post.text %></p> 
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
        	<div class="col-md-12">
                
               <div class="scroller">
                    <% @post.photos.each do |photo| %>
                   <div>
                        <%= image_tag(photo.url, :class => "post-photo") %>
                    </div>
                    <% end %>
               </div>
                
            </div>  
        </div>

   
    </div>  
</div>

app/views/users/index.html.erb
<div class="container user-block text-center">
 <div class="row">
 	<h2>@<%= @user.username %></h2> 
</div>
<div class="row">
    <div class="col-md-4">
        <% if @user.avatar? %>
            <%= image_tag(@user.avatar.url, :class => "avatar") %>
        <% end %>   
    </div>
    <div class="col-md-8 text-center">
        <h3>Имя: <%= @user.name %></h3>
        <h3>Дружит с нами c <%= @user.created_at.strftime('%d.%m.%Y') %> </h3>
    </div>
</div>  
</div>

<div class="row text-center">
    <%= link_to "Редактировать профиль", edit_users_url, :class => "link-button" %>

    <%= link_to "Добавить пост", new_posts_url, :class => "link-button" %>
</div>
        
<div class="container user-block text-center buffer-top">
    <div class="row">
        <% @posts.reverse.each do |post| %>

        <div class="row">
            <% if !post.photos.blank? %>
            <div class="col-md-6">
               <div class="scroller">
                    <% post.photos.each do |photo| %>
                   <div>
                        <%= image_tag(photo.url, :class => "post-photo") %>
                    </div>
                    <% end %>
               </div>
            </div> 

            <div class="col-md-6">
                <div class="post-block">
                    <div class="post-name">
                        <h1><%= post.name %></h1> <h4>   <%= post.created_at.strftime('%d.%m.%Y - %k:%M') %></h4> <br>
                        <%= link_to "Читать полностью", controller: "posts", action: "show", id: post.id %> <%= link_to "Обсуждение", controller: "comments", action: "show", id: post.id %> (<%= post.comments.size %>)
                    </div>
                    <div class="post-text">
                        <p><%= post.text %></p> 
                    </div>
                </div>
            </div>
            <% else %>
            <div class="col-md-12">
                <div class="post-block-full">
                    <div class="post-name">
                        <h1><%= post.name %></h1> <h4>   <%= post.created_at.strftime('%d.%m.%Y - %k:%M') %></h4> <br>
                        <%= link_to "Читать полностью", controller: "posts", action: "show", id: post.id %> <br>
                        <%= link_to "Обсуждение", controller: "comments", action: "show", id: post.id %> (<%= post.comments.size %>)
                    </div>
                    <div class="post-text">
                        <p><%= post.text %></p> 
                    </div>
                </div>
            </div>
            <% end %>
        </div>

    <% end %>
    </div>  
</div>

app/views/users/list.html.erb
<h1 class="text-center">Наши пользователи</h1>

<div class="container">
	<% @users.each do |user| %>
		
			<div class="row comment-block">
				<div class="col-md-2 text-center">
					<%= image_tag(user.avatar.url, :class => "avatar-min") %>
					<h2>@<%= user.username %></h2>
				</div>
				<div class="col-md-10 comment-text">
					<h4>Посты: <%= user.posts.size %></h4> <br>
					<h4>Комментарии: <%= Comment.where(user_id: user.id).size %></h4> <br>
					<h4>Дружит с нами c <%= user.created_at.strftime('%d.%m.%Y') %></h4>
				</div>
			</div>
		
	<% end %>	
</div>

app/views/users/shared/_error_messages.html.erb
<div class="container text-center">
  <div class="row">

<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Войти", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Зарегестрироваться", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забыли пароль?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Не получили инструкцию?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Не получили инструкцию?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Войти с #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container user-block text-center">
 <div class="row">
 	<h2>@<%= @user.username %></h2> 
</div>
<div class="row">
    <div class="col-md-4">
        <% if @user.avatar? %>
            <%= image_tag(@user.avatar.url, :class => "avatar") %>
        <% end %>   
    </div>
    <div class="col-md-8 text-center">
        <h3>Имя: <%= @user.name %></h3>
        <h3>Дружит с нами c <%= @user.created_at.strftime('%d.%m.%Y') %> </h3>
    </div>
</div>  
</div>
        
<div class="container user-block text-center buffer-top">
    <div class="row">
        <% @posts.each do |post| %>

        <div class="row">
            <div class="col-md-4">
               
            </div>  

            <div class="col-md-8">
                <div class="post-block">
                    <div class="post-name">
                        <h1><%= post.name %></h1> <br>
                    </div>
                    <div class="post-text">
                        <p><%= post.text %></p> 
                    </div>
                </div>
            </div>
        </div>



    <% end %>
    </div>  
</div>